blueprint:
  name: Hue Random White Strobe (True Random Parallel)
  description: >
    Each selected Hue light strobes independently with random timing.
  domain: script
  input:
    target_lights:
      name: Target Hue Lights
      description: Select the lights to strobe
      selector:
        entity:
          domain: light
          multiple: true
    flashes:
      name: Number of Flashes
      description: How many times each light should flash
      default: 20
      selector:
        number:
          min: 1
          max: 500
          step: 1
    min_delay:
      name: Minimum Delay (ms)
      default: 100
      selector:
        number:
          min: 10
          max: 2000
          step: 10
    max_delay:
      name: Maximum Delay (ms)
      default: 300
      selector:
        number:
          min: 20
          max: 5000
          step: 10

variables:
  min_d: !input min_delay
  max_d: !input max_delay

sequence:
  - parallel:
      - repeat:
          for_each: !input target_lights
          sequence:
            - repeat:
                count: !input flashes
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ repeat.item }}"
                    data:
                      brightness: 255
                      color_temp: 153
                  - delay: "{{ ((min_d | int) + range(0, (max_d | int - min_d | int + 1) | random)) / 1000 }}"
                  - service: light.turn_off
                    target:
                      entity_id: "{{ repeat.item }}"
                  - delay: "{{ ((min_d | int) + range(0, (max_d | int - min_d | int + 1) | random)) / 1000 }}"
mode: restart
